# Generated by Django 5.0.3 on 2024-03-21 01:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_topic_room_host_message_room_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Channel',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='channel',
        ),
    ]
